// AUTO-GENERATED by NativeFlow. Dynamic UI wiring — edit in Studio, not here.
import * as React from 'react';
import { Text } from 'react-native';
import { DynamicUIView } from '@nativeflow/dynamic-ui-native';
import { apiFetch } from './auth/apiClient';
import { useAuthStore } from './auth/store';
import { appRuntime } from './app';
import { getBorderRadius, getSpacing, getThemeColors } from '../config/theme';

const PAGE_NAMES: Record<string, string> = {"f8caca43-5622-4119-9267-9c39737d4b73":"Login","0c287a5d-f853-4a53-bf43-689ad97ecc57":"Home","54c9bf2f-c22c-4014-80ce-d30365b1ade8":"Accounts","934c139f-33ab-4eb2-b6f8-31d45f7f8d40":"Investments","d7c5d5b7-3ef2-416e-8e16-1165b6e1588a":"Loans","9a327574-76df-49d2-8288-b3061e36aae1":"Payments","c15eaee9-d14b-4938-9a30-974bd7daadb5":"Transactions","f4cd0440-7bf9-4b16-9948-57f8eecfa30e":"AI Mintly","7bff0c20-97fe-4ee2-8ee1-5cec220beb53":"Welcome"};
const CONFIGS: Record<string, any> = {
  "2943c509-94e8-464a-a5ff-8e823c67efc1": {
    "endpoint": "https://wylsvmumemzvltauwqno.supabase.co/functions/v1/nf-dynamic-ui-e9e527",
    "operations": [
      {
        "name": "openANewAccount",
        "description": "Open a new account",
        "inputs": [
          {
            "in": "body",
            "name": "owner_name",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "enum": [
              "checking",
              "savings"
            ],
            "name": "account_type",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "account_number",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "balance",
            "type": "number"
          },
          {
            "in": "body",
            "name": "currency",
            "type": "string"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "recordAManualTransaction",
        "description": "Record a manual transaction",
        "inputs": [
          {
            "in": "body",
            "name": "account_id",
            "type": "string",
            "format": "uuid",
            "required": true
          },
          {
            "in": "body",
            "enum": [
              "credit",
              "debit"
            ],
            "name": "type",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "amount",
            "type": "number",
            "required": true
          },
          {
            "in": "body",
            "name": "description",
            "type": "string"
          },
          {
            "in": "body",
            "name": "category",
            "type": "string"
          },
          {
            "in": "body",
            "name": "merchant",
            "type": "string"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "demoLoginCheckTwoHardcodedUsersNoRLS",
        "description": "Demo login check (two hardcoded users, no RLS)",
        "inputs": [
          {
            "in": "body",
            "name": "p_username",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "p_password",
            "type": "string",
            "required": true
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "addABeneficiaryWhenTheUserEditsThePayeeCardToSomeoneNew",
        "description": "Add a beneficiary (when the user edits the payee card to someone new)",
        "inputs": [
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "name": "name",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "nickname",
            "type": "string"
          },
          {
            "in": "body",
            "name": "upi_id",
            "type": "string"
          },
          {
            "in": "body",
            "name": "account_number",
            "type": "string"
          },
          {
            "in": "body",
            "name": "bank_name",
            "type": "string"
          },
          {
            "in": "body",
            "name": "is_favorite",
            "type": "boolean"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "payByUPIIDOrAccountNumberAfterMPINConfirm",
        "description": "Pay by UPI ID or account number after MPIN confirm",
        "inputs": [
          {
            "in": "body",
            "name": "amount",
            "type": "number",
            "required": true
          },
          {
            "in": "body",
            "name": "mpin",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "upi_id",
            "type": "string",
            "description": "Only for a payee who is not saved. Give exactly one of beneficiary_id, upi_id or account_number."
          },
          {
            "in": "body",
            "name": "account_number",
            "type": "string",
            "description": "Only for a payee who is not saved. Give exactly one of beneficiary_id, upi_id or account_number."
          },
          {
            "in": "body",
            "name": "beneficiary_id",
            "type": "string",
            "format": "uuid",
            "description": "For a saved payee. Give exactly one of beneficiary_id, upi_id or account_number; prefer beneficiary_id and leave the other two out."
          },
          {
            "in": "body",
            "name": "name",
            "type": "string",
            "description": "Payee name shown on the transaction when paying an unsaved UPI ID or account."
          },
          {
            "in": "body",
            "name": "note",
            "type": "string"
          },
          {
            "in": "body",
            "name": "from_account",
            "type": "string",
            "format": "uuid",
            "description": "Defaults to the main account."
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "spendingTotalsAndDailySeriesForAChart",
        "description": "Spending totals and daily series for a chart",
        "inputs": [
          {
            "in": "body",
            "name": "p_account_id",
            "type": "string",
            "format": "uuid",
            "description": "Defaults to the main account."
          },
          {
            "in": "body",
            "name": "p_category",
            "type": "string",
            "description": "Omit for all categories."
          },
          {
            "in": "body",
            "name": "p_from",
            "type": "string",
            "format": "date",
            "description": "Defaults to the first day of this month."
          },
          {
            "in": "body",
            "name": "p_to",
            "type": "string",
            "format": "date",
            "description": "Defaults to today."
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "setAMonthlyLimitUpsertWithOnConflictAccountIdCategory",
        "description": "Set a monthly limit (upsert with on_conflict=account_id,category)",
        "inputs": [
          {
            "in": "query",
            "name": "on_conflict",
            "type": "string"
          },
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "name": "account_id",
            "type": "string",
            "format": "uuid",
            "description": "Defaults to the main account."
          },
          {
            "in": "body",
            "name": "category",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "monthly_limit",
            "type": "number",
            "required": true
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "toggleAutopayFilterWithIdEqUuid",
        "description": "Toggle autopay (filter with id=eq.<uuid>)",
        "inputs": [
          {
            "in": "query",
            "name": "id",
            "type": "string",
            "required": true,
            "description": "eq.<uuid>"
          },
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "name": "autopay",
            "type": "boolean"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "payTheDueAmountOfABill",
        "description": "Pay the due amount of a bill",
        "inputs": [
          {
            "in": "body",
            "name": "biller_id",
            "type": "string",
            "format": "uuid",
            "required": true
          },
          {
            "in": "body",
            "name": "from_account",
            "type": "string",
            "format": "uuid",
            "description": "Defaults to the biller's account."
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "freezeUnfreezeOrChangeCardControlsFilterWithIdEqUuid",
        "description": "Freeze/unfreeze or change card controls (filter with id=eq.<uuid>)",
        "inputs": [
          {
            "in": "query",
            "name": "id",
            "type": "string",
            "required": true,
            "description": "eq.<uuid>"
          },
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "enum": [
              "active",
              "frozen"
            ],
            "name": "status",
            "type": "string"
          },
          {
            "in": "body",
            "name": "online_enabled",
            "type": "boolean"
          },
          {
            "in": "body",
            "name": "international_enabled",
            "type": "boolean"
          },
          {
            "in": "body",
            "name": "contactless_enabled",
            "type": "boolean"
          },
          {
            "in": "body",
            "name": "daily_limit",
            "type": "number"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "fileURLsOfMonthlyStatementsForTheGivenMonths",
        "description": "File URLs of monthly statements for the given months",
        "inputs": [],
        "confirm": "sheet"
      },
      {
        "name": "createASavingGoal",
        "description": "Create a saving goal",
        "inputs": [
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "name": "account_id",
            "type": "string",
            "format": "uuid",
            "description": "Defaults to the main account."
          },
          {
            "in": "body",
            "name": "name",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "emoji",
            "type": "string"
          },
          {
            "in": "body",
            "name": "target_amount",
            "type": "number",
            "required": true
          },
          {
            "in": "body",
            "name": "saved_amount",
            "type": "number",
            "description": "Change it with add_to_goal / withdraw_from_goal"
          },
          {
            "in": "body",
            "name": "target_date",
            "type": "string",
            "format": "date"
          },
          {
            "in": "body",
            "enum": [
              "active",
              "completed",
              "archived"
            ],
            "name": "status",
            "type": "string"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "deleteAGoalFilterWithIdEqUuidWithdrawItsMoneyFirst",
        "description": "Delete a goal (filter with id=eq.<uuid>). Withdraw its money first.",
        "inputs": [
          {
            "in": "query",
            "name": "id",
            "type": "string",
            "required": true,
            "description": "eq.<uuid>"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "editAGoalSNameEmojiTargetOrDateOrArchiveItFilterWithIdEqUuid",
        "description": "Edit a goal's name, emoji, target or date, or archive it (filter with id=eq.<uuid>)",
        "inputs": [
          {
            "in": "query",
            "name": "id",
            "type": "string",
            "required": true,
            "description": "eq.<uuid>"
          },
          {
            "in": "header",
            "name": "Prefer",
            "type": "string"
          },
          {
            "in": "body",
            "name": "name",
            "type": "string"
          },
          {
            "in": "body",
            "name": "emoji",
            "type": "string"
          },
          {
            "in": "body",
            "name": "target_amount",
            "type": "number"
          },
          {
            "in": "body",
            "name": "target_date",
            "type": "string",
            "format": "date"
          },
          {
            "in": "body",
            "enum": [
              "active",
              "archived"
            ],
            "name": "status",
            "type": "string"
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "moveMoneyFromTheAccountIntoAGoalRecordsASavingsDebitCompletesTheGoalAtTarget",
        "description": "Move money from the account into a goal (records a savings debit; completes the goal at target)",
        "inputs": [
          {
            "in": "body",
            "name": "goal_id",
            "type": "string",
            "format": "uuid",
            "required": true
          },
          {
            "in": "body",
            "name": "amount",
            "type": "number",
            "required": true
          }
        ],
        "confirm": "sheet"
      },
      {
        "name": "moveMoneyFromAGoalBackToTheAccountRecordsASavingsCredit",
        "description": "Move money from a goal back to the account (records a savings credit)",
        "inputs": [
          {
            "in": "body",
            "name": "goal_id",
            "type": "string",
            "format": "uuid",
            "required": true
          },
          {
            "in": "body",
            "name": "amount",
            "type": "number",
            "required": true
          }
        ],
        "confirm": "sheet"
      }
    ]
  }
};

/** The themed components ticked for Dynamic UI. Read on every render, so theme colors stay current. */
function looks() {
  return {
    Heading: {
      "Title": { color: "#0F1E4D" },
      "On dark": { color: "#FFFFFF" },
    },
    Card: {
      "Card": { color: "#0F1E4D", padding: 16, borderColor: "#E5E7EB", borderWidth: 1, borderRadius: 20, backgroundColor: "#FFFFFF" },
      "Highlight": { color: "#FFFFFF", padding: 20, borderRadius: 20, backgroundColor: "#0D1B4C" },
      "Soft blue": { color: "#0F1E4D", padding: 16, borderColor: "#C7D2FE", borderWidth: 1, borderRadius: 16, backgroundColor: "#E8EEFF" },
    },
    Badge: {
      "Success": { color: "#16A34A", paddingTop: 4, paddingLeft: 10, borderRadius: 12, paddingRight: 10, paddingBottom: 4, backgroundColor: "#D3F0DE" },
      "Warning": { color: "#B45309", paddingTop: 4, paddingLeft: 10, borderRadius: 12, paddingRight: 10, paddingBottom: 4, backgroundColor: "#FBE6C8" },
      "Danger": { color: "#B91C1C", paddingTop: 4, paddingLeft: 10, borderRadius: 12, paddingRight: 10, paddingBottom: 4, backgroundColor: "#FBDADA" },
      "Info": { color: "#2541B2", paddingTop: 4, paddingLeft: 10, borderRadius: 12, paddingRight: 10, paddingBottom: 4, backgroundColor: "#DCE6FB" },
    },
    Form: {
      "Form": { gap: 12, padding: 16, borderColor: "#E5E7EB", borderWidth: 1, borderRadius: 20, backgroundColor: "#FFFFFF" },
    },
    Box: {
      "Question bubble": { color: "#FFFFFF", paddingTop: 12, paddingLeft: 16, borderRadius: 20, paddingRight: 16, paddingBottom: 12, backgroundColor: "#2F4DE0" },
      "Answer bubble": { gap: 12, color: "#374151", padding: 16, borderColor: "#E5E7EB", borderWidth: 1, borderRadius: 20, backgroundColor: "#FFFFFF" },
    },
    Text: {
      "Body": { color: "#374151" },
      "Muted": { color: "#6B7280" },
      "On dark": { color: "#FFFFFF" },
      "On dark muted": { color: "#AEB8E0" },
    },
    Button: {
      "Primary": { color: "#FFFFFF", paddingTop: 12, paddingLeft: 20, borderRadius: 24, paddingRight: 20, paddingBottom: 12, backgroundColor: "#2F4DE0" },
      "Secondary": { color: "#1E3A8A", paddingTop: 12, borderColor: "#C7D2FE", borderWidth: 1, paddingLeft: 20, borderRadius: 24, paddingRight: 20, paddingBottom: 12, backgroundColor: "#FFFFFF" },
    },
  };
}

const DEFAULT_LOOKS: Record<string, string> = {};

function navigate(pageId: string, params: Record<string, unknown>) {
  const name = PAGE_NAMES[pageId];
  if (name) appRuntime.navigate(name, params);
}

/** The answer stream carries the signed-in user's token, like every other call to the app's API. */
function authHeaders(): Record<string, string> {
  const token = useAuthStore.getState().accessToken;
  return token ? { Authorization: 'Bearer ' + token } : {};
}

type DynamicUIHandle = { ask: (question: string) => void };

// Mounted Dynamic UIs by component id, so an Ask action can reach one.
const MOUNTED = new Map<string, DynamicUIHandle>();

/** Ask a question from the app's own question box. Empty questions are ignored. */
export function ask(nodeId: string, question: unknown) {
  const q = question == null ? '' : String(question);
  if (q.trim()) MOUNTED.get(nodeId)?.ask(q);
}

export function DynamicUI({ id, nodeId, ...rest }: { id: string; nodeId?: string } & Record<string, unknown>) {
  const user = useAuthStore((s: any) => s.user);
  const handle = React.useRef<DynamicUIHandle | null>(null);
  React.useEffect(() => {
    if (!nodeId) return;
    const mine = { ask: (q: string) => handle.current?.ask(q) };
    MOUNTED.set(nodeId, mine);
    return () => {
      if (MOUNTED.get(nodeId) === mine) MOUNTED.delete(nodeId);
    };
  }, [nodeId]);
  const config = CONFIGS[id];
  if (!config) return <Text style={{ color: '#6B7280' }}>This Dynamic UI is not set up yet. Pick a host in Studio.</Text>;
  const me = user ? { id: user.id, email: user.email } : undefined;
  return (
    <DynamicUIView
      ref={handle}
      {...config}
      {...rest}
      authHeaders={authHeaders}
      sessionFetch={apiFetch}
      me={me}
      navigate={navigate}
      looks={looks()}
      defaultLooks={DEFAULT_LOOKS}
    />
  );
}
