// AUTO-GENERATED by NativeFlow. Dynamic UI wiring — edit in Studio, not here.
import * as React from 'react';
import { Text } from 'react-native';
import { DynamicUIView } from '@nativeflow/dynamic-ui-native';
import { apiFetch } from './auth/apiClient';
import { useAuthStore } from './auth/store';
import { appRuntime } from './app';
import { getBorderRadius, getSpacing, getThemeColors } from '../config/theme';

const PAGE_NAMES: Record<string, string> = {"0c287a5d-f853-4a53-bf43-689ad97ecc57":"Home","54c9bf2f-c22c-4014-80ce-d30365b1ade8":"Accounts","934c139f-33ab-4eb2-b6f8-31d45f7f8d40":"Investments","d7c5d5b7-3ef2-416e-8e16-1165b6e1588a":"Loans","9a327574-76df-49d2-8288-b3061e36aae1":"Payments","c15eaee9-d14b-4938-9a30-974bd7daadb5":"Transactions","f4cd0440-7bf9-4b16-9948-57f8eecfa30e":"AI Mintly","f8caca43-5622-4119-9267-9c39737d4b73":"Login","7bff0c20-97fe-4ee2-8ee1-5cec220beb53":"Welcome"};
const CONFIGS: Record<string, any> = {
  "2943c509-94e8-464a-a5ff-8e823c67efc1": {
    "endpoint": "https://wylsvmumemzvltauwqno.supabase.co/functions/v1/nf-dynamic-ui-e9e527",
    "operations": []
  }
};

/** The themed components ticked for Dynamic UI. Read on every render, so theme colors stay current. */
function looks() {
  return {

  };
}

const DEFAULT_LOOKS: Record<string, string> = {};

function navigate(pageId: string, params: Record<string, unknown>) {
  const name = PAGE_NAMES[pageId];
  if (name) appRuntime.navigate(name, params);
}

/** The answer stream carries the signed-in user's token, like every other call to the app's API. */
function authHeaders(): Record<string, string> {
  const token = useAuthStore.getState().accessToken;
  return token ? { Authorization: 'Bearer ' + token } : {};
}

type DynamicUIHandle = { ask: (question: string) => void };

// Mounted Dynamic UIs by component id, so an Ask action can reach one.
const MOUNTED = new Map<string, DynamicUIHandle>();

/** Ask a question from the app's own question box. Empty questions are ignored. */
export function ask(nodeId: string, question: unknown) {
  const q = question == null ? '' : String(question);
  if (q.trim()) MOUNTED.get(nodeId)?.ask(q);
}

export function DynamicUI({ id, nodeId, ...rest }: { id: string; nodeId?: string } & Record<string, unknown>) {
  const user = useAuthStore((s: any) => s.user);
  const handle = React.useRef<DynamicUIHandle | null>(null);
  React.useEffect(() => {
    if (!nodeId) return;
    const mine = { ask: (q: string) => handle.current?.ask(q) };
    MOUNTED.set(nodeId, mine);
    return () => {
      if (MOUNTED.get(nodeId) === mine) MOUNTED.delete(nodeId);
    };
  }, [nodeId]);
  const config = CONFIGS[id];
  if (!config) return <Text style={{ color: '#6B7280' }}>This Dynamic UI is not set up yet. Pick a host in Studio.</Text>;
  const me = user ? { id: user.id, email: user.email } : undefined;
  return (
    <DynamicUIView
      ref={handle}
      {...config}
      {...rest}
      authHeaders={authHeaders}
      sessionFetch={apiFetch}
      me={me}
      navigate={navigate}
      looks={looks()}
      defaultLooks={DEFAULT_LOOKS}
    />
  );
}
