// AUTO-GENERATED by NativeFlow. Voice input, recognized on the device.
import * as React from 'react';
import { Alert } from 'react-native';
import { ExpoSpeechRecognitionModule } from 'expo-speech-recognition';

type Options = { lang?: string; onText: (text: string) => void };

let listening = false;
const watchers = new Set<(on: boolean) => void>();
let subs: { remove(): void }[] = [];

function setListening(on: boolean) {
  listening = on;
  watchers.forEach((w) => w(on));
}

function done() {
  subs.forEach((s) => s.remove());
  subs = [];
  setListening(false);
}

/** Whether the mic is on, so a mic button can show a stop icon. */
export function useListening(): boolean {
  const [on, setOn] = React.useState(listening);
  React.useEffect(() => {
    watchers.add(setOn);
    setOn(listening);
    return () => { watchers.delete(setOn); };
  }, []);
  return on;
}

/** Ends listening and says why on screen. */
function fail(message: string) {
  done();
  Alert.alert('Voice input', message);
}

const MESSAGES: Record<string, string> = {
  'no-speech': "Didn't catch that. Tap the mic and try again.",
  'speech-timeout': "Didn't catch that. Tap the mic and try again.",
  'not-allowed': 'Allow the microphone and speech recognition in Settings to talk instead of type.',
  'service-not-allowed': 'Speech recognition is turned off on this device.',
  'language-not-supported': 'This language is not available for speech recognition on this device.',
  network: 'Speech recognition needs an internet connection on this device.',
};

export async function start({ lang, onText }: Options) {
  if (listening) return;
  setListening(true);
  try {
    if (!ExpoSpeechRecognitionModule.isRecognitionAvailable()) return fail('Speech recognition is not available on this device.');
    const perm = await ExpoSpeechRecognitionModule.requestPermissionsAsync();
    if (!perm.granted) return fail(MESSAGES['not-allowed']);
    subs = [
      ExpoSpeechRecognitionModule.addListener('result', (e) => {
        if (__DEV__) console.log('[voice] result', e.isFinal, e.results[0]?.transcript);
        const text = e.results[0]?.transcript;
        if (text != null) onText(text);
      }),
      ExpoSpeechRecognitionModule.addListener('error', (e) => {
        if (__DEV__) console.log('[voice] error', e.error, e.message);
        if (e.error === 'aborted') return done();
        fail(MESSAGES[e.error] ?? `Voice input stopped (${e.error}). ${e.message}`);
      }),
      ExpoSpeechRecognitionModule.addListener('end', () => {
        if (__DEV__) console.log('[voice] end');
        done();
      }),
    ];
    if (__DEV__) console.log('[voice] start', lang || 'en-US');
    ExpoSpeechRecognitionModule.start({ lang: lang || 'en-US', interimResults: true, addsPunctuation: true });
  } catch (e: any) {
    fail(`Voice input could not start. ${e?.message ?? e}`);
  }
}

/** Stops listening; the last words still arrive as a final result. */
export function stop() {
  if (listening) ExpoSpeechRecognitionModule.stop();
}

/** One mic button: the first tap listens, the next one stops. */
export function toggle(options: Options) {
  return listening ? stop() : start(options);
}
