// AUTO-GENERATED by NativeFlow. Voice input, recognized on the device.
import * as React from 'react';
import { Alert } from 'react-native';
import { ExpoSpeechRecognitionModule } from 'expo-speech-recognition';

type Options = { lang?: string; onText: (text: string) => void };

let listening = false;
const watchers = new Set<(on: boolean) => void>();
let subs: { remove(): void }[] = [];

function setListening(on: boolean) {
  listening = on;
  watchers.forEach((w) => w(on));
}

function done() {
  subs.forEach((s) => s.remove());
  subs = [];
  setListening(false);
}

/** Whether the mic is on, so a mic button can show a stop icon. */
export function useListening(): boolean {
  const [on, setOn] = React.useState(listening);
  React.useEffect(() => {
    watchers.add(setOn);
    setOn(listening);
    return () => { watchers.delete(setOn); };
  }, []);
  return on;
}

export async function start({ lang, onText }: Options) {
  if (listening) return;
  setListening(true);
  const perm = await ExpoSpeechRecognitionModule.requestPermissionsAsync();
  if (!perm.granted) {
    setListening(false);
    Alert.alert('Microphone is off', 'Allow the microphone and speech recognition in Settings to talk instead of type.');
    return;
  }
  subs = [
    ExpoSpeechRecognitionModule.addListener('result', (e) => {
      const text = e.results[0]?.transcript;
      if (text != null) onText(text);
    }),
    ExpoSpeechRecognitionModule.addListener('error', (e) => {
      if (e.error !== 'aborted' && e.error !== 'no-speech') console.warn('[voice]', e.error, e.message);
      done();
    }),
    ExpoSpeechRecognitionModule.addListener('end', done),
  ];
  ExpoSpeechRecognitionModule.start({ lang: lang || 'en-US', interimResults: true, addsPunctuation: true });
}

/** Stops listening; the last words still arrive as a final result. */
export function stop() {
  if (listening) ExpoSpeechRecognitionModule.stop();
}

/** One mic button: the first tap listens, the next one stops. */
export function toggle(options: Options) {
  return listening ? stop() : start(options);
}
