// AUTO-GENERATED by NativeFlow. Voice input, recognized by Sarvam Saaras.
// 22 Indian languages and English; the language is detected unless an action sets one.
import * as React from 'react';
import { Alert, Platform } from 'react-native';
import { AudioModule, AudioQuality, IOSOutputFormat, requestRecordingPermissionsAsync, setAudioModeAsync } from 'expo-audio';
import { apiFetch } from './auth/apiClient';

const STT_URL = "https://wylsvmumemzvltauwqno.supabase.co/functions/v1/nf-dynamic-ui-e9e527/speech";

// Sarvam takes at most 30 seconds per request.
const MAX_MS = 29_000;

// Mono 16 kHz, the rate Sarvam recommends.
const OPTIONS = {
  sampleRate: 16000,
  numberOfChannels: 1,
  bitRate: 64000,
  isMeteringEnabled: false,
  ...Platform.select({
    ios: { extension: '.m4a', outputFormat: IOSOutputFormat.MPEG4AAC, audioQuality: AudioQuality.HIGH, linearPCMBitDepth: 16, linearPCMIsBigEndian: false, linearPCMIsFloat: false },
    android: { extension: '.m4a', outputFormat: 'mpeg4', audioEncoder: 'aac' },
    default: { extension: '.webm', mimeType: 'audio/webm', bitsPerSecond: 64000 },
  }),
};

const MESSAGES = {
  denied: 'Allow the microphone in Settings to talk instead of type.',
  empty: "Didn't catch that. Tap the mic and try again.",
};

type Options = { lang?: string; onText: (text: string) => void };

export type VoiceState = 'idle' | 'recording' | 'sending';

let state: VoiceState = 'idle';
const watchers = new Set<(s: VoiceState) => void>();
let recorder: any = null;
let timer: ReturnType<typeof setTimeout> | null = null;
let current: Options | null = null;

function setState(next: VoiceState) {
  state = next;
  watchers.forEach((w) => w(next));
}

function done() {
  if (timer) clearTimeout(timer);
  timer = null;
  try { recorder?.release?.(); } catch {}
  recorder = null;
  current = null;
  setState('idle');
}

/** 'recording' while the mic is on, 'sending' while the words are on their way. */
export function useVoiceState(): VoiceState {
  const [s, setS] = React.useState(state);
  React.useEffect(() => {
    watchers.add(setS);
    setS(state);
    return () => { watchers.delete(setS); };
  }, []);
  return s;
}

/** Whether the mic is on or the words are on their way. */
export function useListening(): boolean {
  return useVoiceState() !== 'idle';
}

/** Ends listening and says why on screen. */
function fail(message: string) {
  done();
  Alert.alert('Voice input', message);
}

export async function start({ lang, onText }: Options) {
  if (state !== 'idle') return;
  setState('recording');
  current = { lang, onText };
  try {
    const perm = await requestRecordingPermissionsAsync();
    if (!perm.granted) return fail(MESSAGES.denied);
    await setAudioModeAsync({ allowsRecording: true, playsInSilentMode: true });
    // Made outside a hook, so the mic works from any action.
    recorder = new (AudioModule as any).AudioRecorder(OPTIONS);
    await recorder.prepareToRecordAsync();
    recorder.record();
    timer = setTimeout(() => { void stop(); }, MAX_MS);
    if (__DEV__) console.log('[voice] recording', lang || 'auto');
  } catch (e: any) {
    fail(`Voice input could not start. ${e?.message ?? e}`);
  }
}

/** Stops recording and sends the audio; the words arrive through onText. */
export async function stop() {
  if (state !== 'recording' || !recorder || !current) return;
  setState('sending');
  const { lang, onText } = current;
  const rec = recorder;
  if (timer) clearTimeout(timer);
  timer = null;
  try {
    await rec.stop();
    await setAudioModeAsync({ allowsRecording: false });
    const uri: string | null = rec.uri;
    if (!uri) return fail(MESSAGES.empty);
    const text = await transcribe(uri, lang);
    if (!text.trim()) return fail(MESSAGES.empty);
    onText(text);
    done();
  } catch (e: any) {
    fail(`Voice input stopped. ${e?.message ?? e}`);
  }
}

async function transcribe(uri: string, lang?: string): Promise<string> {
  const form = new FormData();
  if (Platform.OS === 'web') {
    const blob = await (await fetch(uri)).blob();
    form.append('file', blob, 'speech.webm');
  } else {
    // An m4a must be labelled audio/mp4, or Sarvam refuses it.
    form.append('file', { uri, name: 'speech.m4a', type: 'audio/mp4' } as any);
  }
  // Without a language Saaras detects it.
  if (lang) form.append('language_code', lang);
  const res = await apiFetch(STT_URL, { method: 'POST', body: form });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data?.error ?? `Speech service error ${res.status}`);
  if (__DEV__) console.log('[voice] result', data.language_code, data.transcript);
  return data.transcript ?? '';
}

/** One mic button: the first tap records, the next one sends. */
export function toggle(options: Options) {
  if (state === 'sending') return;
  return state === 'recording' ? stop() : start(options);
}
