-- Auto-generated by NativeFlow auth-codegen. Do not edit by hand.
-- Roles table + has_role helper. Created first so the SQL-language
-- function below resolves on a fresh project (it fails at creation time if
-- the table is missing). SECURITY DEFINER with a pinned search_path.
create table if not exists public."user_roles" (
  user_id uuid not null references auth.users (id) on delete cascade,
  "role" text not null,
  primary key (user_id, "role")
);

-- The roles table decides who is an admin, so it is itself protected: a
-- signed-in user may read their own rows and nothing else. No insert/update/
-- delete policy exists, so with RLS on, client writes are denied outright —
-- grant roles from the service role or SQL editor.
alter table public."user_roles" enable row level security;
drop policy if exists "nf_roles_self_read" on public."user_roles";
create policy "nf_roles_self_read" on public."user_roles"
  for select to authenticated using (user_id = auth.uid());

create or replace function public.has_role(_user_id uuid, _role text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public."user_roles"
    where user_id = _user_id and "role" = _role
  )
$$;

